name: Create issue

on:
  workflow_dispatch:
    inputs:
      doi:
        description: "Digital Object Identifier (DOI)"
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-doi-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create Issue
      uses: actions-ecosystem/action-create-issue@v1
      with:
        github_token: ${{ env.GITHUB_TOKEN }}
        title: ${{ github.event.inputs.doi }}
        body: my new issue
