name: "Create issue: Publish manuscript"

on:
  workflow_dispatch:
    inputs:
      doi:
        description: "Digital Object Identifier (DOI)"
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-doi-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: imjohnbo/extract-issue-template-fields@v1
      id: extract
      with:
        path: .github/ISSUE_TEMPLATE/publish_manuscript.md

    - name: "Create issue: Publish manuscript ${{ github.event.inputs.doi }}"
      uses: imjohnbo/issue-bot@v3
      with:
        title: ${{ steps.extract.outputs.title | replace("[DOI]", github.event.inputs.doi) }}
        body: ${{ steps.extract.outputs.body | replace("[DOI]", github.event.inputs.doi) }}
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
