name: "Create issue: Publish manuscript"

on:
  workflow_dispatch:
    inputs:
      doi:
        description: "Digital Object Identifier (DOI)"
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-doi-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: "Create issue: Publish manuscript ${{ github.event.inputs.doi }}"
      uses: imjohnbo/issue-bot@v3
      with:
        title: "Publish manuscript ${{ github.event.inputs.doi }}"
        body: |
          ### Test body title

          Add things to discuss below
        project-v2-path: users/nlisgo/projects/2
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
