name: "Create issue: Publish manuscript"

on:
  workflow_dispatch:
    inputs:
      doi:
        description: "Digital Object Identifier (DOI)"
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-doi-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: imjohnbo/extract-issue-template-fields@v1
      id: extract
      with:
        path: .github/ISSUE_TEMPLATE/publish_manuscript.md

    - name: Replace DOI placeholder
      run: |
        echo "::set-env name=TITLE::$(echo "${{ steps.extract.outputs.title }}" | sed 's/\[DOI\]/${{ github.event.inputs.doi }}/g')"
        echo "::set-env name=BODY::$(echo "${{ steps.extract.outputs.body }}" | sed 's/\[DOI\]/${{ github.event.inputs.doi }}/g')"

    - name: "Create issue: Publish manuscript ${{ github.event.inputs.doi }}"
      uses: imjohnbo/issue-bot@v3
      with:
        title: "${{ env.TITLE }}"
        body: "${{ env.BODY }}"
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
