name: "Create issue: Publish manuscript"

on:
  workflow_dispatch:
    inputs:
      doi:
        description: "Digital Object Identifier (DOI)"
        required: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create-doi-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - uses: imjohnbo/extract-issue-template-fields@v1
      id: extract
      with:
        path: .github/ISSUE_TEMPLATE/publish_manuscript.md

    - uses: bluwy/substitute-string-action@v1
      id: sub-title
      with:
        _input-text: "${{ steps.extract.outputs.title }}"
        '[DOI]': "${{ github.event.inputs.doi }}"

    - uses: bluwy/substitute-string-action@v1
      id: sub-body
      with:
        _input-text: "${{ steps.extract.outputs.body }}"
        '[DOI]': "${{ github.event.inputs.doi }}"

    - name: "Create issue: Publish manuscript ${{ github.event.inputs.doi }}"
      uses: imjohnbo/issue-bot@v3
      with:
        title: "${{ steps.sub-title.outputs.result }}"
        body: "${{ steps.sub-body.outputs.result }}"
        project-type: user
        project: 3
        column: Todo
        token: ${{ secrets.PAT }}
