name: Create issue

on:
  workflow_dispatch:
    inputs:
      doi:
        description: "Digital Object Identifier (DOI)"
        required: true

jobs:
  create-doi-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate token
      id: generate_token
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.PRIVATE_KEY }}

    - name: Create issue
      uses: imjohnbo/issue-bot@v3
      env:
        TOKEN: ${{ steps.generate_token.outputs.token }}
      with:
        title: "Publish manuscript ${{ github.event.inputs.doi }}"
        body: |
          ### Test body title

          Add things to discuss below
        token: ${{ env.TOKEN }}
